### ISSUE TITLE
Endpoint creation is failing

### ISSUE THREAD

**Issue by marurcs** [dhawalkp/dolly-12b#1]
Hi, 

I tried running the code in Sagemaker studio with the same instance and kernel. But the endpoint creation is failing after around 19 minutes. I tried using `"InstanceType": "ml.g4dn.16xlarge"`  but the endpoint creation fails. I gave a try with `dolly-v2-7b ` and `dolly-v2-3b ` without any success. Not sure if this is due to the size of the model or anything else that I'm missing.

Thank you
Marur

**Comment by dhawalkp** [comment]
Fixed it. It was because of typo mistake in setting the value of option.task in serving.properties during PR merge

**Comment by marurcs** [comment]
Thanks for your response. The endpoint creation is still failing and the cloud log gives the following response
`java.util.concurrent.CompletionException: ai.djl.engine.EngineException: GPU devices are not enough to run 4 partitions.`

Is it because I'm using a `ml.g5.8xlarge` instance which has a single GPU and in the serving.properties file `tensor_parallel_degree=4`? 

If yes, can the script run on `ml.g5.8xlarge` instance by modifying the tensor_parallel_degree=4` to tensor_parallel_degree=1`?
